version: 2
updates:
- package-ecosystem: maven
  directory: "/api/AppPrevisaoTempo"
  schedule:
    interval: daily
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: org.jboss.resteasy:resteasy-jaxrs
    versions:
    - 3.15.0.Final
  - dependency-name: org.hibernate:hibernate-core
    versions:
    - 5.4.27.Final
    - 5.4.28.Final
  - dependency-name: org.hibernate:hibernate-entitymanager
    versions:
    - 5.4.27.Final
    - 5.4.28.Final
  - dependency-name: org.apache.commons:commons-lang3
    versions:
    - "3.11"
